[versions]
actito-services = "1.0.0-SNAPSHOT"
kotlin = "2.0.0"
android-gradle-api = "7.3.0"
google-gson = "2.10.1"
mavenPublish = "0.34.0"

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle-api" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
