blank_issues_enabled: false
contact_links:
  - name: Actito Documentation
    url: https://developers.actito.com/
    about: Check the documentation for help with the integration.
  - name: Actito Support
    url: https://www.actito.com/en-BE/contact/support/
    about: Contact Actito Support for technical support.
